// import mongoose from "mongoose";
// import dotenv from "dotenv";
// import Accommodation from "./models/Accommodation.js";

// dotenv.config();

// // Debugging: Print MONGO_URI to ensure it's loaded
// console.log("MONGO_URI:", process.env.MONGO_URI);

// if (!process.env.MONGO_URI) {
//     console.error("Error: MONGO_URI is not defined in .env file.");
//     process.exit(1); // Exit script
// }

// // Connect to MongoDB
// mongoose.connect(process.env.MONGO_URI, {
//     useNewUrlParser: true,
//     useUnifiedTopology: true,
// })
// .then(() => {
//     console.log("MongoDB connected successfully!");
//     return Accommodation.insertMany(sampleAccommodations);
// })
// .then(() => {
//     console.log("Sample data inserted successfully!");
//     mongoose.connection.close();
// })
// .catch((error) => {
//     console.error("Error inserting sample data:", error);
//     mongoose.connection.close();
// });

// const sampleAccommodations = [
//     {
//         id: 1,
//         title: "Luxury Beach Studio",
//         type: "Entire Apartment",
//         location: "Cape Town",
//         description: "A beautiful beachfront studio apartment with stunning views of the Hout Bay Valley and the Helderberg mountains beyond.",
//         guests: 2,
//         bedrooms: 1,
//         bathrooms: 1,
//         price: 1886,
//         amenities: ["WiFi", "Pool", "Parking"],
//         images: ["https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886931/cpt-img-0.5_ff0mxc.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886929/cpt-img-0.2_ybbfmg.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886932/cpt-img-0.3_uhydxz.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886932/cpt-img-0.1_y1i0lg.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886933/cpt-img-0.4_qmtrxi.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886933/cpt-img-0_mvtcqd.png"],
//         host: "Amahle Hani",
//         hostId: '67d4365b69c3f11a7d476ce5',
//         rating: 4.94,
//         reviews: 364,
//         weeklyDiscount: 0,
//         cleaningFee: 275,
//         serviceFee: 1830,
//         occupancyTaxes: 283,
//         specifics: {
//             cleanliness: 4.9,
//             communication: 4.9,
//             checkIn: 5.0,
//             accuracy: 5.0,
//             location: 4.9,
//             value: 4.9,
//         },
//     },
//     {
//         id: 2,
//         title: "The Loft at 33",
//         type: "Private Room",
//         location: "Cape Town",
//         description: "Beautiful loft bedroom with seperate entrance. Situated on the second floor of the family house, quiet and tranquil.",
//         guests: 2,
//         bedrooms: 1,
//         bathrooms: 1,
//         price: 586,
//         amenities: ["WiFi", "Pool", "Parking"],
//         images: ["https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886930/cpt-img-1_lybxzw.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886931/cpt-img-1.1_qyjpbo.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886929/cpt-img-1.2_qpnbbh.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886928/cpt-img-1.3_nioqn7.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886932/cpt-img-1.4_rwlo6z.png"],
//         host: "Amahle Hani",
//         hostId: '67d4365b69c3f11a7d476ce5',
//         rating: 4.91,
//         reviews: 32,
//         weeklyDiscount: 0,
//         cleaningFee: 0,
//         serviceFee: 476,
//         occupancyTaxes: 88,
//         specifics: {
//             cleanliness: 4.9,
//             communication: 5.0,
//             checkIn: 5.0,
//             accuracy: 4.9,
//             location: 4.9,
//             value: 4.9,
//         },
//     },
//     {
//         id: 3,
//         title: "LeeHome AirBnb",
//         type: "Shared Room",
//         location: "Cape Town",
//         description: "Peaceful retreat in Parklands North, Sandown. Enjoy the tranquility of a family-friendly environment with a patio, braai area, and pool. Just a stone's throw away from the beach!",
//         guests: 2,
//         bedrooms: 1,
//         bathrooms: 1,
//         price: 549,
//         amenities: ["WiFi", "Pool", "Parking"],
//         images: ["https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886919/cpt-img-3_wzoxfq.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886928/cpt-img-3.1_qrvkn2.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886920/cpt-img-3.2_yqegvw.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886916/cpt-img-3.3_vmnfyn.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886916/cpt-img-3.4_nqrrna.png"],
//         host: "Amahle Hani",
//         hostId: '67d4365b69c3f11a7d476ce5',
//         rating: 5.0,
//         reviews: 6,
//         weeklyDiscount: 0,
//         cleaningFee: 0,
//         serviceFee: 446,
//         occupancyTaxes: 82,
//         specifics: {
//             cleanliness: 5.0,
//             communication: 5.0,
//             checkIn: 4.8,
//             accuracy: 5.0,
//             location: 5.0,
//             value: 5.0,
//         },
//     },
//     {
//         id: 4,
//         title: "Appart 'Paris Orly-Stade France-Charles De Gaulle",
//         type: "Entire Apartment",
//         location: "Paris",
//         description: "Chic, cozy apartment 3 minutes walk away from a mini supermarket, bakery, pharmacy, and a bank. Great for couples, friends or family!",
//         guests: 4,
//         bedrooms: 1,
//         bathrooms: 1,
//         price: 855,
//         amenities: ["WiFi", "Pool", "Parking"],
//         images: ["https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886914/prs-img-0_aqmmhe.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886913/prs-img-0.1_moh2ut.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886912/prs-img-0.2_brfzng.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886913/prs-img-0.3_i4jvhu.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886914/prs-img-0.4_s5gwhh.jpg"],
//         host: "Stephanie Ludovic",
//         hostId: '67d43800ff7c77b9b44783b9',
//         rating: 4.6,
//         reviews: 5,
//         weeklyDiscount: 0,
//         cleaningFee: 799,
//         serviceFee: 957,
//         occupancyTaxes: 128,
//         specifics: {
//             cleanliness: 4.8,
//             communication: 4.4,
//             checkIn: 4.4,
//             accuracy: 4.8,
//             location: 4.6,
//             value: 4.6,
//         },
//     },
//     {
//         id: 5,
//         title: "Loggia aux portes de Paris",
//         type: "Shared Room",
//         location: "Paris",
//         description: "Modern eco-friendly and comfortable shared home on the doorstep of Paris. We can't wait to welcome you to Paris soon!!",
//         guests: 2,
//         bedrooms: 1,
//         bathrooms: 1,
//         price: 593,
//         amenities: ["WiFi", "Pool", "Parking"],
//         images: ["https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886909/prs-img-1_civigm.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886910/prs-img-1.2_qs1yhx.jpg", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886909/prs-img-1.1_lfk2zz.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886907/prs-img-1.3_onyxhe.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886909/prs-img.1.4_vurwrl.jpg"],
//         host: "Stephanie Ludovic",
//         hostId: '67d43800ff7c77b9b44783b9',
//         rating: 5.0,
//         reviews: 4,
//         weeklyDiscount: 461,
//         cleaningFee: 200,
//         serviceFee: 821,
//         occupancyTaxes: 89,
//         specifics: {
//             cleanliness: 4.8,
//             communication: 5.0,
//             checkIn: 5.0,
//             accuracy: 5.0,
//             location: 4.8,
//             value: 5.0,
//         },
//     },
//     {
//         id: 6,
//         title: "Villa Tenjin chambre 17",
//         type: "Private Room",
//         location: "Paris",
//         description: "Quiet and stylish home with all modern comforts",
//         guests: 2,
//         bedrooms: 1,
//         bathrooms: 1,
//         price: 699,
//         amenities: ["WiFi", "Pool", "Parking"],
//         images: ["https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886907/prs-img-2_suic9y.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886907/prs-img-2.1_predib.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886906/prs-img-2.2_kz4yys.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886906/prs-img-2.3_x7udyd.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886907/prs-img-2.4_uwkgdv.jpg"],
//         host: "Stephanie Ludovic",
//         hostId: '67d43800ff7c77b9b44783b9',
//         rating: 4.81,
//         reviews: 96,
//         weeklyDiscount: 0,
//         cleaningFee: 459,
//         serviceFee: 0,
//         occupancyTaxes: 105,
//         specifics: {
//             cleanliness: 4.6,
//             communication: 4.8,
//             checkIn: 4.9,
//             accuracy: 4.9,
//             location: 4.5,
//             value: 4.8,
//         },
//     },
//     {
//         id: 7,
//         title: "SIAM | Condo Sukhumvit, MRT Queen Sirikit",
//         type: "Entire Apartment",
//         location: "Thailand",
//         description: "Modern apartment on the 33rd floor with full access to the sky pool, gym, and sauna.",
//         guests: 2,
//         bedrooms: 1,
//         bathrooms: 1,
//         price: 1005,
//         amenities: ["WiFi", "Pool", "Parking"],
//         images: ["https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886903/tha-img-0_fcnvax.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886903/tha-img-0.1_h7r1dg.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886904/tha-img-0.2_vuuuaq.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886903/tha-img-0.3_p0iv5l.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886902/tha-img-0.4_r5zu0s.png"],
//         host: "Pattanan",
//         hostId: '67d4387abba43a9bff48d480',
//         rating: 4.81,
//         reviews: 113,
//         weeklyDiscount: 0,
//         cleaningFee: 652,
//         serviceFee: 1071,
//         occupancyTaxes: 151,
//         specifics: {
//             cleanliness: 4.9,
//             communication: 4.8,
//             checkIn: 4.9,
//             accuracy: 4.8,
//             location: 4.7,
//             value: 4.8,
//         },
//     },
//     {
//         id: 8,
//         title: "Kunna House",
//         type: "Private Room",
//         location: "Thailand",
//         description: "If you want to relax in a quiet place in the middle of nature, Kanna house is the perfect place for your stay.",
//         guests: 2,
//         bedrooms: 1,
//         bathrooms: 1,
//         price: 706,
//         amenities: ["WiFi", "Pool", "Parking"],
//         images: ["https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886901/tha-img-1_fdxcko.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886902/tha-img-1.2_a856n3.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886902/tha-img-1.1_euvibn.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886903/tha-img-1.3_cwjo78.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886902/tha-img-1.4_vlcrn0.png"],
//         host: "Pattanan",
//         hostId: '67d4387abba43a9bff48d480',
//         rating: 5.0,
//         reviews: 22,
//         weeklyDiscount: 0,
//         cleaningFee: 0,
//         serviceFee: 666,
//         occupancyTaxes: 106,
//         specifics: {
//             cleanliness: 5.0,
//             communication: 4.8,
//             checkIn: 5.0,
//             accuracy: 5.0,
//             location: 4.9,
//             value: 5.0,
//         },
//     },
//     {
//         id: 9,
//         title: "Modern House in Makham Tia",
//         type: "Shared Room",
//         location: "Thailand",
//         description: "Cozy, ambient rooms 27km away fromthe airport and 15 minutes to Lomprayah Tapee Pier.",
//         guests: 2,
//         bedrooms: 1,
//         bathrooms: 1,
//         price: 271,
//         amenities: ["WiFi", "Pool", "Parking"],
//         images: ["https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886902/tha-img-2_nvi956.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886906/tha-img-2.1_axbaoq.jpg", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886902/tha-img-2.2_omt7zm.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886902/tha-img-2.5_rxjdju.png", "https://res.cloudinary.com/dn48jdzzm/image/upload/v1741886902/tha-img-2.4_coyjpb.png"],
//         host: "Pattanan",
//         hostId: '67d4387abba43a9bff48d480',
//         rating: 4.95,
//         reviews: 59,
//         weeklyDiscount: 0,
//         cleaningFee: 0,
//         serviceFee: 0,
//         occupancyTaxes: 41,
//         specifics: {
//             cleanliness: 5.0,
//             communication: 5.0,
//             checkIn: 5.0,
//             accuracy: 5.0,
//             location: 4.3,
//             value: 4.9,
//         },
//     },
// ];

// Accommodation.insertMany(sampleAccommodations).then(() => {
//     console.log("Sample data inserted!");
//     mongoose.connection.close();
// });
